plugins {
    id 'org.openjfx.javafxplugin' version '0.0.13'
    id 'java'
}

apply plugin: 'java'
apply plugin: 'application'

mainClassName = 'main'
sourceCompatibility = 16
targetCompatibility = 16
version = '1.0'

repositories {
    mavenCentral()
    maven {
        url "https://maven.google.com"
    }
}

dependencies {
    implementation 'org.openjfx:javafx-controls:21.0.2'
    implementation 'org.openjfx:javafx-graphics:21.0.2'
    implementation 'org.openjfx:javafx-base:21.0.2'
    implementation 'org.openjfx:javafx-fxml:21.0.2'
    implementation 'org.openjfx:javafx-media:21.0.2'
    implementation 'org.apache.commons:commons-lang3:3.13.0'
    implementation 'com.opencsv:opencsv:5.9'
    implementation 'io.fair-acc:chartfx:11.3.1'
    implementation 'ch.qos.logback:logback-classic:1.4.12'
}

javafx {
    version = "21.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.media']
}

test {
    testLogging.showStandardStreams = true
}
